name: colorizer
description: A class that converts, cyphers and handles Colors
version: 0.0.1
publish_to: none
homepage: https://github.com/RagehAz/colorizer.git

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^3.0.8
  numeric:
    git:
      url: https://github.com/RagehAz/numeric.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
